import { burgerBtn } from './ui/burger.js';
import { settingsBtnClick } from './ui/settingsBtn.js';
import { itemClick } from './ui/sidebarNav.js';
import { themeBtnClick } from './ui/themeBtn.js';
import { apiFetch } from './api/api.js';
apiFetch();
burgerBtn();
settingsBtnClick();
itemClick();
themeBtnClick();